"""create_initial_schema

Revision ID: 355e93861898
Revises: 
Create Date: 2026-09-14 14:58:07.860396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355e93861898'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer_sentiment',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('timestamp_utc', sa.String(length=50), nullable=False),
    sa.Column('review_sentiment_score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumer_sentiment', schema=None) as batch_op:
        batch_op.create_index('idx_consumer_ticker_time', ['ticker', 'timestamp_utc'], unique=False)

    op.create_table('coordination_scores',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('window_start_utc', sa.String(length=50), nullable=False),
    sa.Column('window_end_utc', sa.String(length=50), nullable=True),
    sa.Column('ks_component', sa.Float(), nullable=True),
    sa.Column('acf_component', sa.Float(), nullable=True),
    sa.Column('onset_component', sa.Float(), nullable=True),
    sa.Column('duplicate_ratio', sa.Float(), nullable=True),
    sa.Column('sentiment_variance', sa.Float(), nullable=True),
    sa.Column('coordination_score', sa.Float(), nullable=True),
    sa.Column('confidence_flag', sa.String(length=32), nullable=True),
    sa.Column('computed_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'window_start_utc')
    )
    with op.batch_alter_table('coordination_scores', schema=None) as batch_op:
        batch_op.create_index('idx_coord_ticker_time', ['ticker', 'window_start_utc'], unique=False)

    op.create_table('duplicate_pairs',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('window_start_utc', sa.String(length=50), nullable=False),
    sa.Column('post_id_a', sa.String(length=128), nullable=False),
    sa.Column('post_id_b', sa.String(length=128), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'window_start_utc', 'post_id_a', 'post_id_b')
    )
    op.create_table('index_values',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('window_start_utc', sa.String(length=50), nullable=False),
    sa.Column('window_end_utc', sa.String(length=50), nullable=True),
    sa.Column('rn', sa.Float(), nullable=True),
    sa.Column('rn_confidence', sa.Float(), nullable=True),
    sa.Column('cirg', sa.Float(), nullable=True),
    sa.Column('cli', sa.Float(), nullable=True),
    sa.Column('cassi', sa.Float(), nullable=True),
    sa.Column('vdi', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'window_start_utc')
    )
    op.create_table('narrative_phylogeny',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('window_start_utc', sa.String(length=50), nullable=False),
    sa.Column('window_end_utc', sa.String(length=50), nullable=True),
    sa.Column('parent_window_start_utc', sa.String(length=50), nullable=True),
    sa.Column('mutation_type', sa.String(length=64), nullable=False),
    sa.Column('mutation_detail', sa.Text(), nullable=True),
    sa.Column('composite_delta', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'window_start_utc')
    )
    with op.batch_alter_table('narrative_phylogeny', schema=None) as batch_op:
        batch_op.create_index('idx_phylogeny_ticker_time', ['ticker', 'window_start_utc'], unique=False)

    op.create_table('periodicity_stats',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('window_start_utc', sa.String(length=50), nullable=False),
    sa.Column('window_end_utc', sa.String(length=50), nullable=False),
    sa.Column('ks_statistic', sa.Float(), nullable=True),
    sa.Column('acf_peak_lag_minutes', sa.Float(), nullable=True),
    sa.Column('acf_peak_strength', sa.Float(), nullable=True),
    sa.Column('dominant_frequency_minutes', sa.Float(), nullable=True),
    sa.Column('onset_dispersion_index', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'window_start_utc')
    )
    op.create_table('raw_posts',
    sa.Column('post_id', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp_utc', sa.String(length=50), nullable=False),
    sa.Column('community', sa.String(length=128), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('scraped_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('post_id')
    )
    with op.batch_alter_table('raw_posts', schema=None) as batch_op:
        batch_op.create_index('idx_account_ticker', ['account_id', 'ticker'], unique=False)
        batch_op.create_index('idx_ticker_time', ['ticker', 'timestamp_utc'], unique=False)

    op.create_table('ticker_time_bins',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('bin_start_utc', sa.String(length=50), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'bin_start_utc')
    )
    op.create_table('ticker_window_metrics',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('window_start_utc', sa.String(length=50), nullable=False),
    sa.Column('window_end_utc', sa.String(length=50), nullable=True),
    sa.Column('rn', sa.Float(), nullable=True),
    sa.Column('rn_confidence', sa.Float(), nullable=True),
    sa.Column('cirg', sa.Float(), nullable=True),
    sa.Column('cli', sa.Float(), nullable=True),
    sa.Column('cassi', sa.Float(), nullable=True),
    sa.Column('vdi', sa.Float(), nullable=True),
    sa.Column('coordination_score', sa.Float(), nullable=True),
    sa.Column('confidence_flag', sa.String(length=32), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('dominant_index', sa.String(length=32), nullable=True),
    sa.Column('risk_flags', sa.Text(), nullable=True),
    sa.Column('aggregation_confidence', sa.String(length=32), nullable=True),
    sa.Column('computed_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'window_start_utc')
    )
    with op.batch_alter_table('ticker_window_metrics', schema=None) as batch_op:
        batch_op.create_index('idx_twm_ticker_time', ['ticker', 'window_start_utc'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('post_timing',
    sa.Column('post_id', sa.String(length=128), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('timestamp_utc', sa.String(length=50), nullable=False),
    sa.Column('delta_seconds', sa.Float(), nullable=True),
    sa.Column('is_first_mention', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['raw_posts.post_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    with op.batch_alter_table('post_timing', schema=None) as batch_op:
        batch_op.create_index('idx_timing_ticker_time', ['ticker', 'timestamp_utc'], unique=False)

    op.create_table('reasoning_trace',
    sa.Column('trace_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('window_start_utc', sa.String(length=50), nullable=False),
    sa.Column('post_id', sa.String(length=128), nullable=False),
    sa.Column('contributed_to', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['raw_posts.post_id'], ),
    sa.PrimaryKeyConstraint('trace_id')
    )
    with op.batch_alter_table('reasoning_trace', schema=None) as batch_op:
        batch_op.create_index('idx_trace_ticker_time', ['ticker', 'window_start_utc'], unique=False)

    op.create_table('text_features',
    sa.Column('post_id', sa.String(length=128), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=32), nullable=True),
    sa.Column('capitulation_flag', sa.Integer(), nullable=True),
    sa.Column('capitulation_confidence', sa.Float(), nullable=True),
    sa.Column('is_sarcastic', sa.Integer(), nullable=True),
    sa.Column('irony_adjusted_sentiment', sa.Float(), nullable=True),
    sa.Column('conviction_hedge_ratio', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('computed_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['raw_posts.post_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_features')
    with op.batch_alter_table('reasoning_trace', schema=None) as batch_op:
        batch_op.drop_index('idx_trace_ticker_time')

    op.drop_table('reasoning_trace')
    with op.batch_alter_table('post_timing', schema=None) as batch_op:
        batch_op.drop_index('idx_timing_ticker_time')

    op.drop_table('post_timing')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('ticker_window_metrics', schema=None) as batch_op:
        batch_op.drop_index('idx_twm_ticker_time')

    op.drop_table('ticker_window_metrics')
    op.drop_table('ticker_time_bins')
    with op.batch_alter_table('raw_posts', schema=None) as batch_op:
        batch_op.drop_index('idx_ticker_time')
        batch_op.drop_index('idx_account_ticker')

    op.drop_table('raw_posts')
    op.drop_table('periodicity_stats')
    with op.batch_alter_table('narrative_phylogeny', schema=None) as batch_op:
        batch_op.drop_index('idx_phylogeny_ticker_time')

    op.drop_table('narrative_phylogeny')
    op.drop_table('index_values')
    op.drop_table('duplicate_pairs')
    with op.batch_alter_table('coordination_scores', schema=None) as batch_op:
        batch_op.drop_index('idx_coord_ticker_time')

    op.drop_table('coordination_scores')
    with op.batch_alter_table('consumer_sentiment', schema=None) as batch_op:
        batch_op.drop_index('idx_consumer_ticker_time')

    op.drop_table('consumer_sentiment')
    # ### end Alembic commands ###
